---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml

- name: Proxmox Mail Gateway
  hosts: all   # should be limited
  become: true
  gather_facts: yes
  roles:
    - ansibleguy.sw_proxmox_mail_gw
