---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - 'community.crypto'

roles:
  - name: 'oxlorg.nginx'
    src: 'git+https://github.com/O-X-L/ansible-role-nginx'

  - name: 'oxlorg.certs'
    src: 'git+https://github.com/O-X-L/ansible-role-certs'
