---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - 'community.crypto'

roles:
  - src: 'ansibleguy.infra_certs'
  - src: 'ansibleguy.infra_nginx'
