---

- name: Proxmox Mail GW | Showing debug info - user provided config
  ansible.builtin.debug:
    var: pmg
  when:
    - debug is defined
    - debug

- name: Proxmox Mail GW | Showing debug info - running config
  ansible.builtin.debug:
    var: PMG_CONFIG
  when:
    - debug is defined
    - debug

- name: Proxmox Mail GW | Checking config
  ansible.builtin.assert:
    that:
      - pmg is defined
      - pmg.fqdn | valid_hostname

- name: Proxmox Mail GW | Checking environment
  ansible.builtin.assert:
    that:
      - "ansible_virtualization_role is undefined or ansible_virtualization_role != 'guest' or 'docker' not in ansible_virtualization_tech_guest"
  when: not testing

- name: Proxmox Mail GW | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
