---

- name: Converge - default
  hosts: test-ag-pmg-1
  vars:
    no_prompts: true
    pmg:
      fqdn: 'pmg1.test.ansibleguy.net'

      nginx:
        aliases: ['alias.lan', '_']
        ip: '192.168.7.2'
        ssl:
          mode: 'ca'

  roles:
    - ansibleguy.sw_proxmox_mail_gw

- name: Converge - no nginx
  hosts: test-ag-pmg-2
  vars:
    no_prompts: true
    subscription: true
    pmg:
      fqdn: 'pmg2.test.ansibleguy.net'

      manage:
        webserver: false

  roles:
    - ansibleguy.sw_proxmox_mail_gw
