---

# todo: full testing using VMs => docker isn't working

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-ag-pmg-1
    docker_networks:
      - name: 'test-ag-pmg'
        ipam_config:
          - subnet: '192.168.7.0/24'
            gateway: '192.168.7.254'
    networks:
      - name: 'test-ag-pmg'
        ipv4_address: '192.168.7.2'
    groups: [grp_targets]
    docker_host: 'tcp://molecule-docker.local:2375'
    # docker_host: 'unix://var/run/docker.sock'  # localhost
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  #  - name: test-ag-pmg-tester
  #    networks:
  #      - name: 'test-ag-pmg'
  #        ipv4_address: '192.168.7.1'
  #    etc_hosts: {
  #      pmg1.test.oxl.at: '192.168.7.2',
  #      pmg2.test.oxl.at: '192.168.7.3',
  #    }
  #    groups: [grp_tester]
  #    <<: *docker_all

  - name: test-ag-pmg-2
    networks:
      - name: 'test-ag-pmg'
        ipv4_address: '192.168.7.3'
    groups: [grp_targets]
    docker_host: 'tcp://molecule-docker.local:2375'
    # docker_host: 'unix://var/run/docker.sock'  # localhost
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify  # MUST NOT make changes
    - idempotence
    - check
    - destroy
